  on:
    push:
      branches: [ main, develop ]
    pull_request:
      branches:
        - main
        - develop
  jobs:
    build:
      runs-on: ubuntu-latest
      name: Checkout code
      steps:
        - uses: actions/checkout@v4
        - run: |
            echo "Checking out code"
            apt install sl
            sl